### ISSUE TITLE
Issues with strings left in amenity drop down box. Prevents user from proceeding to next step

### ISSUE THREAD

**Issue by carolinatorrescity** [CityOfPhiladelphia/MyPPR#15]
User fails to write-in amenity needed - types "au" for auditorium but does not clear it after amenity has been found. Page has issues in processing "au" in amenity field. User later removes it to continue adding program. 
User continues to have problems entering attendance into the website. Follow up might be useful.

**Comment by andrewviren** [comment]
as seen in #609 - Oktavia Cherry
