### ISSUE TITLE
As a MyPPR Staff I want to be able to report when there is no fee for my program

### ISSUE THREAD

**Issue by carolinatorrescity** [CityOfPhiladelphia/MyPPR#16]
Programs at both Jacobs and Torresdale entered with a $1 fee, this maybe because user was confused about fee amount.

**Comment by andrewviren** [comment]
Fixed. Submitting issue to Knack

**Comment by andrewviren** [comment]
Change #data/object_5/fields/field_54 to "When FEE is lower than 0"
![screen shot 2017-06-07 at 2 50 13 pm](https://user-images.githubusercontent.com/719422/26895805-c354c38c-4b90-11e7-9b28-09f8dad7e0da.png)
