### ISSUE TITLE
Please add the following to PPRstat

### ISSUE THREAD

**Issue by carolinatorrescity** [CityOfPhiladelphia/MyPPR#20]
Vincent Picariell
Matthew Morrow
G. Gaul
Bruce B. Rush
Tamara Harrity

**Comment by carolinatorrescity** [comment]
Also please add Patricia McCole. Thanks

**Comment by andrewviren** [comment]
Issue moved to [andrewviren/PPRstat #9](https://github.com/andrewviren/PPRstat/issues/9) via [**ZenHub**](https://www.zenhub.com/)
