### ISSUE TITLE
As a MyPPR user, I want to be able to update my profile information from any screen using the Knack defaults

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/MyPPR#23]

**Comment by andrewviren** [comment]
create replacement for /knack-account/

**Comment by andrewviren** [comment]
https://www.knack.com/blog/introducing-user-pages

**Comment by andrewviren** [comment]
Move the data from "My Profile" page to the Account Settings Page

**Comment by andrewviren** [comment]
move content on #pages/scene_288 to #pages/scene_302 (account settings)

**Comment by mirosado** [comment]
Updated Changes folder. Needs review.
