### ISSUE TITLE
Add to PPRstat

### ISSUE THREAD

**Issue by carolinatorrescity** [CityOfPhiladelphia/MyPPR#25]
Matthew McMorrow - McIlvain Playground

**Comment by carolinatorrescity** [comment]
Jameele Mitchell to Wister Playground

"Hut/Old Building" must be added to amenity at Emanuel Rec Center - Requested by Azaraha Robinson

**Comment by andrewviren** [comment]
Matthew McMorrow needs to be added to PPRstat's permit view as a permit approver

**Comment by andrewviren** [comment]
Issue moved to [andrewviren/PPRstat #6](https://github.com/andrewviren/PPRstat/issues/6) via [**ZenHub**](https://www.zenhub.com/)
