### ISSUE TITLE
As a PPR staff person, I want to be able to view where one of my colleagues is assigned and their (facility) contact information, so that I can contact them.

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/MyPPR#27]

**Comment by andrewviren** [comment]
have consistent navigation

**Comment by andrewviren** [comment]
can we separate out governance facility vs. programmed facility?
i.e. how do we separate who can change information about a facility vs. who is assigned to a given facility

**Comment by mirosado** [comment]
Updated changes folder. Needs Review.
