### ISSUE TITLE
I am a parent, guardian, or caregiver.  am trying to find programs, activities, and events for my family and me. I am in need of the service because I am looking for after school programs, food assistance programs, casual weekend activities, sports, and summer camps.

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/MyPPR#37]

**Comment by andrewviren** [comment]
KEY QUESTIONS

- What kid-friendly activities/events are occurring in the city?
- How close are they to my house or neighborhood?
- Is SEPTA and/or parking nearby?
- Where are the bathrooms?
- Are there nearby places to eat?
- What programs or rec centers are in my neighborhood or the vicinity?
- Do they cost money?
- Do you transport the students from school to the recreation center?
- Do you offer meals?
- What are the hours?
- Is the space safe?
- Is the neighborhood safe?

**Comment by carolinatorrescity** [comment]
Could not find PPR information regarding food assistance programs.
