### ISSUE TITLE
As a MyPPR Staff, I want my programs to automatically be marked as inactive so that I can more easily manage my programs

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/MyPPR#42]

**Comment by andrewviren** [comment]
Hint: table task

**Comment by andrewviren** [comment]
use scheduled end date as end date

**Comment by andrewviren** [comment]
check every day if something ended today.

**Comment by andrewviren** [comment]
check every day if something started today (second task)

**Comment by andrewviren** [comment]
add table filter to This Facility page to view inactive programs and mark them active

**Comment by mirosado** [comment]
Updated changes folder. Needs Review.
