### ISSUE TITLE
As a MyPPR User, I want to be able to understand each MyPPR form field's purpose so that I can provide the most accurate information possible.

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/MyPPR#46]

**Comment by andrewviren** [comment]
Start by reviewing and updating descriptions of all form fields.

**Comment by andrewviren** [comment]
Forms include:

- [x] Program Submission
- [x] Program Schedule Submission
- [x] Program Attendance Submission 
- [x] Facility Amenity Edit
- [x] Program Edit
- [x] Program Schedule Edit

**Comment by andrewviren** [comment]
capture: URL, FieldTitle, and FieldDescription in a CSV file to track changes

**Comment by mirosado** [comment]
Updated changes folder. Needs Review.

**Comment by andrewviren** [comment]
https://github.com/andrewviren/MyPPR/blob/knack_miguel_test/changes/46.md
