### ISSUE TITLE
Facility supervisors would like to see a list of programs for their facility.  

### ISSUE THREAD

**Issue by Darrenef** [CityOfPhiladelphia/MyPPR#91]
List should include program name, to/from dates, gender, cost, age range, approved status, and active status.

Similar to:

https://ppr.knack.com/myppr#programs-for-approval/

**Comment by andrewviren** [comment]
@Darrenef can you provide any clarification?

**Comment by Darrenef** [comment]
Hey Andy,

This would be a way for rec leaders to see all the programs they've uploaded to MyPPR. Some leaders expressed frustration at not being able to see their entire list of programs. I thought we could adapt the list I use for program approval.
